version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/mysql/data:/var/lib/mysql

  app:
    build: .
    container_name: devopscontainer
    depends_on:
      - mysqldb
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/stationSki?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update",
        "management.endpoints.web.exposure.include" : "*",
        "management.endpoint.health.show-details": "always",
        "management.endpoint.prometheus.enabled": "true"
      }'
    command:
      - --allow-public-key-retrieval=true
      - --cors-allowed-origins=*
    volumes:
      - .:/root/.m2
    ports:
      - 9090:9090

volumes:
  db_data: